### ISSUE TITLE
Use sales_order_save_commit_after event

### ISSUE THREAD

**Issue by joachimVT** [mage-os/mageos-common-async-events#10]
Hi 

I am using the mageos-common-async-events module to dispatch a webhook call when a new order is placed is. 
The event sales_order_save_after fires, but it  fails when the consumer is trying to fetch the order by order ID. Despite having the correct order ID in the observer, when the consumer is trying to fetch the order, it returns an error: `The entity that was requested doesn't exist. Verify the entity and try again`. 

This is apparently because all *_save_after observers allow for modification of the entity in question before MySQL commits it to the database, where as *_save_commit_after observers waits until after the MySQL transaction has been committed.
Since we don't want to modify the order, and instead we want to wait until after it's been saved completely in the DB, it would be better to use `sales_order_save_commit_after` instead of `order_save_after`.

What do you think

**Comment by avstudnitz** [comment]
@joachimVT Sounds reasonable. I'll test that and make the changes when I get to it. Otherwise, I'd be happy to receive a Pull Request from you :-)
Does the same apply to the `sales_order_shipment_save_after`, `sales_order_invoice_save_after` and `sales_order_creditmemo_save_after` events?

**Comment by joachimVT** [comment]
Hi @avstudnitz I can make a PR for this change. I didn't test the other events, but the same logic applies for the other entities I think.

**Comment by gowrizrh** [comment]
@joachimVT if you'd like to open a PR for this, i'll assign this issue to you.

**Comment by joachimVT** [comment]
@gowrizrh yess I will create a PR for this, didn't have the time yet.

**Comment by avstudnitz** [comment]
@joachimVT Did you get to this yet? I can take over if you don't have the time for that right now.
